In [8]:
# for

# for in <collection>
#       <loop body>



for v1 in range(10): # 0 ~ 9
    print('v1 is :', v1)
    
print()

for v2 in range(1, 11): # 1 ~ 10
    print('v2 is :', v2)

print()

for v3 in range(1, 11, 2):
    print('v3 is :', v3)
    
    
print()

sum1 = 0
for v in range(1, 1001):
    sum1 += v
    
print('1 ~ 1000 Sum :', sum1)


# sum() 이용
print('1 ~ 1000 Sum :', sum(range(1, 1001)))
# range() --> class<range>    내부적으로 list를 생성한다
print('1 ~ 1000 4의 배수의 합 :', sum(range(4, 1001, 4)))

v1 is : 0
v1 is : 1
v1 is : 2
v1 is : 3
v1 is : 4
v1 is : 5
v1 is : 6
v1 is : 7
v1 is : 8
v1 is : 9

v2 is : 1
v2 is : 2
v2 is : 3
v2 is : 4
v2 is : 5
v2 is : 6
v2 is : 7
v2 is : 8
v2 is : 9
v2 is : 10

v3 is : 1
v3 is : 3
v3 is : 5
v3 is : 7
v3 is : 9

1 ~ 1000 Sum : 500500
1 ~ 1000 Sum : 500500
1 ~ 1000 4의 배수의 합 : 125500

In [1]:
# Iteratble 자료형
# 문자열, 리스트, 튜플, 집합, 사전(딕셔너리)
# iterable 리턴 함수: range, reversed, enumerate, filter, map, zip

# 1
names = ['Kim', 'Park', 'Cho', 'Lee', 'Choi', 'Yoo']

for n in names:
    print('You are :', n)
    
# 2
lotto_numbers = [11, 19, 21, 28, 36, 37]

for n in lotto_numbers:
    print('Current numebr : ', n)
    
    
# 3
word = 'Beautiful'

for s in word:
    print('word: ', s)
    
    
# 4
my_info = {
    "name": "Lee",
    "Age": 33,
    "City": "Seoul"
}

for k in my_info:
    print('key: ',k)
    print('val: ', my_info[k])
    print('get(key): ', my_info.get(k))
    
for v in my_info.values():
    print('values :', v)
    
# 5
name = 'PineAppLE'

for n in name:
    if n.isupper():
        print(n)
    else:
        print(n.upper())

You are : Kim
You are : Park
You are : Cho
You are : Lee
You are : Choi
You are : Yoo
Current numebr :  11
Current numebr :  19
Current numebr :  21
Current numebr :  28
Current numebr :  36
Current numebr :  37
word:  B
word:  e
word:  a
word:  u
word:  t
word:  i
word:  f
word:  u
word:  l
key:  name
val:  Lee
get(key):  Lee
key:  Age
val:  33
get(key):  33
key:  City
val:  Seoul
get(key):  Seoul
values : Lee
values : 33
values : Seoul
P
I
N
E
A
P
P
L
E

In [3]:
# break
numbers = [14, 3, 4, 7, 10 ,24, 17, 2, 33, 15, 34 ,36, 38]


# !! for else 구문
for num in numbers:
    if num == 56:
        print('Found: 56!')
        break
else:
    print('Not Found : ', num)
        
# continue
lt = ["1", 2, 5, True, 4.3, complex(4)]

for v in lt:
    if type(v) is bool:
        continue
    print('current type: ', v, type(v))
    print('multipy by 2', v * 3)  # Tue *3 = 3 여기서는 continue

Not Found :  38
current type:  1 <class 'str'>
multipy by 2 111
current type:  2 <class 'int'>
multipy by 2 6
current type:  5 <class 'int'>
multipy by 2 15
current type:  4.3 <class 'float'>
multipy by 2 12.899999999999999
current type:  (4+0j) <class 'complex'>
multipy by 2 (12+0j)

In [6]:
# 구구단 
for i in range(2, 10):
    for j in range(1, 10):
        print('{:4d}'.format(i * j), end ='') # 4자리의 정수형, end옵션을 줄바꿈 막기, loop 한번 돌고 end하면
    print() # 줄바꿈
    

# 변환 예제
name2 = 'Aceman'

print('Reversed', reversed(name2))
print('List', list(reversed(name2)))
print('Set', set(reversed(name2))) # 순서 x

   2   4   6   8  10  12  14  16  18
   3   6   9  12  15  18  21  24  27
   4   8  12  16  20  24  28  32  36
   5  10  15  20  25  30  35  40  45
   6  12  18  24  30  36  42  48  54
   7  14  21  28  35  42  49  56  63
   8  16  24  32  40  48  56  64  72
   9  18  27  36  45  54  63  72  81
Reversed <reversed object at 0x000001B3E385B640>
List ['n', 'a', 'm', 'e', 'c', 'A']
Set {'c', 'm', 'e', 'a', 'A', 'n'}